config/routes.rb
Rails.application.routes.draw do
  resources :compliments, only: [:show]
  resources :donations, only: [:create]
  get 'complimentme' => 'compliments#index'
  get 'family' => 'high_voltage/pages#show', id: 'family'
  get ':slug' => 'organizations#show', as: 'organization'
  root to: 'high_voltage/pages#show', id: 'landing'
end

app/models/compliment.rb
class Compliment < ActiveRecord::Base
  validates :message, presence: true

  def self.random
    order("random()").limit(1).first
  end

  def message_share_url
    share_options = {
      text: "#{message}. Send someone else a compliment:",
      url: "https://www.julianandmichellegiveback.com/complimentme"
    }
    "https://twitter.com/intent/tweet?#{share_options.to_param}"
  end
end

app/models/donation.rb
class Donation < ActiveRecord::Base
  validates :organization, presence: true
  belongs_to :organization
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  validates :name, presence: true
  validates :slug, presence: true
  validates :info_url, presence: true
  validates :donation_url, presence: true
  validates :sort_order, presence: true

  has_many :donations

  def to_param
    slug
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/compliments_controller.rb
class ComplimentsController < ApplicationController

  def index
    @compliment = Compliment.random
  end

  def show
    @compliment = if params[:id] == 'random'
      Compliment.random
    else
      Compliment.find(params[:id])
    end
    render json: @compliment
  end

end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController

  def create
    @donation = Donation.new(donation_params)

    if @donation.save
      DonationMailer.new_donation_email(@donation).deliver_now
      redirect_to @donation.organization.donation_url
    else
      redirect_to :back
    end
  end

private

  def donation_params
    params.require(:donation).permit(:name, :email, :amount, :organization_note, :personal_note, :organization_id)
  end

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

  def show
    @organization = Organization.find_by_slug!(params[:slug])
    @compliment = Compliment.random
    @donation = @organization.donations.build
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/compliments/_twitter_share_js.html.slim
javascript:
  window.twttr=(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],t=window.twttr||{};
  if(d.getElementById(id))return t;js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";
  fjs.parentNode.insertBefore(js,fjs);t._e=[];t.ready=function(f){t._e.push(f);};return t;}(document,"script","twitter-wjs"));

app/views/compliments/index.html.slim
.compliment-page
  section.body-content-container.wrap-container

    h2.compliment.js-compliment-message
      = @compliment.message

    .compliment-refresh
      a class="js-compliment-reloader" href="#" Hit me with a new compliment

    .compliment-cta
      a href="/" class="compliment-cta-button"
        | OK, that's enough. I want to donate!
      a class="twitter popup js-compliment-share-url send" href="#{@compliment.message_share_url}" 
        | Send someone a compliment
        .send-icon
= render 'twitter_share_js'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Giveback</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- for Facebook -->
  <meta property="og:title" content="Project Give Back" />
  <meta property="og:image" content="<%= image_url 'giveback-preview.png' %>" />
  <meta property="og:url" content="<%= request.original_url %>" />
  <meta property="og:description" content="Sometimes, the best gift is giving back. We know you love us a lot, so instead of giving us something for us, we’d love if you’d consider giving to an organization that we support." />
  <link rel="shortcut icon" href="/favicon.png" type="image/x-icon">
  <%= favicon_link_tag %>
  <script src="//use.typekit.net/qky6yzy.js"></script>
  <script>try{Typekit.load();}catch(e){}</script>
</head>
<body>

<%= yield %>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<%= javascript_include_tag 'application' %>
<%= render 'layouts/partials/analytics' %>
</body>
</html>

app/views/layouts/partials/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-47260751-3', 'auto');
  ga('send', 'pageview');
</script>

app/views/layouts/partials/_global_footer.html.slim
footer.global-footer
  .wrap-container
    .footer-image
      = image_tag("gifts.png")
    .footer-content
      ' Site designed and built by
      a> href="http://twitter.com/mvenetucci" target="_blank" Michelle
      ' and
      a href="http://twitter.com/jatescher" target="_blank" Julian
      | .
    .footer-content
      ' Built with Rails, Bourbon, and Neat, and hosted on Heroku. Source code on
      a href="https://github.com/venetucci/giveback" target="_blank" Github
      |.

app/views/layouts/partials/_global_nav.html.slim
header.global-nav
  .wrap-container
    .logo
      a href="/" GIVE BACK
    = link_to "compliment me", complimentme_path, class: "nav-cta"

app/views/organizations/show.html.slim
= render "layouts/partials/global_nav"

.details-hero
  section.body-content-container.wrap-container
    h3.details-hero-title
      ' So, you're interested in donating to
      ' #{link_to "#{@organization.name}", @organization.info_url}

    .details-hero-text
      p
        | We’re about to send you off to the donations page. Before you go, would you like to let us know that you donated?
      .details-hero-caret
        = link_to(image_tag("caret.png"), '#', id: 'organization-header-link')


= form_for @donation, html: { id: 'form', class: 'details-form' } do |f|
  = f.hidden_field :organization_id
  section.body-content-container.wrap-container
    h3.details-form-title id='donation-form'
      | Leave Us A Note
    h5.details-form-subtitle
      | This form is just for us. #{@organization.name} won’t see this information. All information is optional.

    .details-form-field
      .details-form-field-half
        = f.label :name, class: 'details-form-field-title'
          | What's your name?
        = f.text_field :name, class: 'details-form-field-box'

      .details-form-field-half
        = f.label :email, class: 'details-form-field-title'
          | What's your email address?
        = f.text_field :email, class: 'details-form-field-box'

    .details-form-field-full

      = f.label :name, class: 'details-form-field-title'
        | Are you planning to leave a note in the donation? What will it be?
      = f.text_area :organization_note, class: 'details-form-field-box', rows: "4"

      = f.label :name, class: 'details-form-field-title'
        | Would you like to leave us a note?
      = f.text_area :personal_note, class: 'details-form-field-box', rows: "4"

      = f.submit 'Submit form and donate', class: "details-form-cta"
      = f.submit 'Continue without form', class: "details-form-cta-blank"

= render "layouts/partials/global_footer"

app/views/pages/complimentme.html.slim
section.body-content-container.wrap-container

  h2.compliment
    | You are a generous and wise person

  .compliment-refresh
    a href="" Hit me with a new compliment

  .compliment-cta
    .compliment-cta-button
      a href="/" OK, that's enough. I want to donate!
    .send
      a class="twitter popup" href="http://twitter.com/share?text=Send%20someone%20a%20compliment:" Send someone a compliment
      .send-icon

app/views/pages/details.html.slim
.details-hero
  section.body-content-container.wrap-container
    h3.details-hero-title
      | So you're interested in donating to Black Girls Code.
    .details-hero-link
      | I haven't made my decision yet, I want to 
      a href="http://www.blackgirlscode.com/"target="_blank" learn more
      |.

    .details-hero-text
      p.details-hero-compliment
        | You look rather dashing today.
        span.details-hero-compliment-refresh
      p
        | We’re about to send you off to the donations page. Don’t worry, you can always come back and donate to other organizations. 
      p
        | Before you go, would you like to let us know that you donated? 

      .details-hero-yes
        .details-hero-yes-text
          | Yes
        span.details-hero-yes-arrow

.details-form
  section.body-content-container.wrap-container
    h3.details-form-title
      | Leave Us A Note
    h5.details-form-subtitle
      | This form is just for us. Black Girls Code won’t see this information. All of this information is optional. 

    .details-form-field
      .details-form-field-half
        .details-form-field-title
          | What's your name?
        input.details-form-field-box

      .details-form-field-half
        .details-form-field-title
          | What's your email address?

        input.details-form-field-box

    .details-form-field-full
      .details-form-field-title
        | How much are you planning to donate?
      input.details-form-field-box

      .details-form-field-title
        | Are you planning to leave a note in the donation? What will it be?
      input.details-form-field-box

      .details-form-field-title
        | Would you like to leave us a note?
      input.details-form-field-box

      .details-form-cta
        a href="https://www.paypal.com/us/cgi-bin/webscr?cmd=_flow&SESSION=Rk57jqpZH8gWI0Q90Q6xx_upzUhwf2E69qQvw9B0-g8MIE05VtBcgJqpNgm&dispatch=5885d80a13c0db1f8e263663d3faee8de62a88b92df045c56447d40d60b23a7c" target="_blank" Submit form and donate
      .details-form-cta-addendum
        | (It's ok if it's empty!)

app/views/pages/family.html.slim
section.family-background
  .body-content-container.wrap-container
      .family
        .family-section-one
          .family-section-one-image
          .family-section-one-content
            .family-content-text
              | We have a little 
              .highlight.highlight-color announcement
              |. On March 20, 2015, we 
              .highlight.highlight-color got married
              |  at the San Francisco Courthouse. We didn’t tell anyone until afterwards. We took a lot of selfies and we both wore 
              .highlight.highlight-color jeans
              |.
        .family-content-text
          = link_to image_tag("michelle.png", class: "michelle"), "http://twitter.com/mvenetucci",
            target: "_blank"
          | and
          = link_to image_tag("julian.png", class: "julian"),
            "http://twitter.com/jatescher",
            target: "_blank"
          | met while attending the University of Washington in 2009 after being set-up by their mutual friend, Seihyun. She still takes all the credit for their relationship. The two moved to the Bay Area after graduating.
        .family-section-two
          .family-section-two-image
          .family-content-text
            .highlight Julian
            |  co-founded WillCall out of college, and ran it successfully for 4 years before it was acquired by Ticketfly in San Francisco. He’s currently a senior software engineer at Ticketfly and is focused on building out an amazing engineering team. 
          .family-content-text
            .highlight Michelle 
            |  worked as a program manager at a sustainable food non-profit for a couple of years before taking a hard right into product design and front-end development. She’s currently a Product Designer at thoughtbot and spends her free time learning how to build iOS apps.
          .family-content-text.highlight-centered
            | find Julian: 
            a href="http://www.twitter.com/jatescher" target="_blank" Twitter
            |, 
            a href="http://juliantescher.com" target="_blank" Website 
            |  / 
            | find Michelle: 
            a href="http://www.twitter.com/mvenetucci" target="_blank" Twitter
            |, 
            a href="http://www.michelle.codes" target="_blank" Website
            |, 
            a href="http://dribbble.com/mvenetucci" target="_blank" Dribbble

          .family-content-text.highlight.highlight-centered
            | Fun Tidbits
          .family-content-text
            | Julian and Michelle are both adding each other’s last name to their middle names. Yes, the length of Michelle’s name has now reached ridiculous proportions and she’s dragging Julian down with her. 
          .family-names
            .family-names-item Michelle Ann Tescher Venetucci-Harvey
            .family-names-item Julian Anthony Venetucci Tescher
          .family-content-text
            | Their wedding bands were custom made by an artist in San Francisco out of gold recycled from computers.
          .family-content-text
            | March 20th was the start of Spring and the Vernal Equinox, as well as International Happiness Day. 

          .family-content-text.highlight.highlight-centered
            | Questions for Michelle and Julian
          .family-section-three-image
          .family-section-one-content
            .family-content-text
              .highlight.highlight-color Why Elope? 
              |  We decided to go the non-traditional route. This wasn’t a quick decision; it was made for reasons we feel very strongly about, and was something we decided over a number of years. We could probably write a book about all the reasons we made this decision. We’re more than happy to chat about this if anyone is curious. 
        .family-content-text
          .highlight.highlight-color What about gifts?
          |  We feel pretty fortunate in our life and would like to start a tradition of giving back. We are not asking for any gifts, but if you’d like to send something our way, we’d love if you’d consider giving to an organization that we support in lieu of a gift. This is important to us as a couple; we even made a website dedicated to this and started everything off with a donation to each organization on our list.
        .family-content-text.highlight-centered
          .family-content-cta
            a href="/" Visit our donation site

= render "layouts/partials/global_footer"

app/views/pages/landing.html.slim
section.hero
  .body-content-container.wrap-container
    .hero-image
      = image_tag("michelleandjulian.png")
    .hero-content
      h1.hero-title
      .hero-main-text
        p
          ' Philanthropy is better than gifts. A project by
          a> href="http://twitter.com/mvenetucci" target="_blank" Michelle
          ' and
          a href="http://twitter.com/jatescher" target="_blank" Julian
          | .
        a.hero-cta href="#" id="organizations-link" Organizations we like

section.organization id="organizations"
  .wrap-container
    h3.organization-title
      | Organizations We Like
    h5.organization-subtitle
      ' Feel free to donate in our name. Or not. Just tell these great organizations to
      a href="http://i3.kym-cdn.com/photos/images/newsfeed/000/264/241/9e9.gif" take your money
      |.
  .wrap-container
    - Organization.where(hidden: false).order(:sort_order).all.each do |organization|
      .organization-card
        h4.organization-card-title
          = organization.name
        - if organization.featured_content.present?
          .featured-content-tag
            | featured
          .featured-content
            = organization.featured_content
          .featured-progress-bar
            .featured-progress-bar-current
              | current
            .featured-progress-bar-goal
              | goal: $25,000
        .organization-card-text
          = organization.description
        = link_to organization.reason_to_donate, organization, class: 'organization-card-cta'

= render "layouts/partials/global_footer"